<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::insert([
            [
                'category_id' => 1,
                'name' => 'ASUS ROG Strix G16',
                'brand' => 'ASUS',
                'model' => 'ROG Strix G16',
                'price' => 1499.99,
                'stock' => 10,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Gaming laptop with strong performance.',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i7',
                'screen_size' => '16 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'ASUS TUF F15',
                'brand' => 'ASUS',
                'model' => 'TUF F15',
                'price' => 1099.99,
                'stock' => 12,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Durable gaming laptop.',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i7',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Dell XPS 13',
                'brand' => 'Dell',
                'model' => 'XPS 13',
                'price' => 1299.99,
                'stock' => 8,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Premium ultrabook laptop.',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i7',
                'screen_size' => '13.4 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Dell Inspiron 15',
                'brand' => 'Dell',
                'model' => 'Inspiron 15',
                'price' => 749.99,
                'stock' => 18,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Reliable everyday laptop.',
                'ram' => '8GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i5',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Acer Aspire 5',
                'brand' => 'Acer',
                'model' => 'Aspire 5',
                'price' => 599.99,
                'stock' => 20,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Affordable laptop for students.',
                'ram' => '8GB',
                'storage' => '512GB SSD',
                'processor' => 'AMD Ryzen 5',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Acer Nitro 5',
                'brand' => 'Acer',
                'model' => 'Nitro 5',
                'price' => 899.99,
                'stock' => 14,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Gaming laptop with powerful GPU.',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i7',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'HP Pavilion 15',
                'brand' => 'HP',
                'model' => 'Pavilion 15',
                'price' => 699.99,
                'stock' => 16,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Stylish laptop for work and study.',
                'ram' => '8GB',
                'storage' => '512GB SSD',
                'processor' => 'Intel Core i5',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'HP Victus 16',
                'brand' => 'HP',
                'model' => 'Victus 16',
                'price' => 999.99,
                'stock' => 11,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Gaming laptop with RTX graphics.',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'processor' => 'AMD Ryzen 7',
                'screen_size' => '16 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Lenovo IdeaPad 3',
                'brand' => 'Lenovo',
                'model' => 'IdeaPad 3',
                'price' => 549.99,
                'stock' => 22,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'Budget friendly laptop.',
                'ram' => '8GB',
                'storage' => '256GB SSD',
                'processor' => 'Intel Core i3',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Lenovo Legion 5',
                'brand' => 'Lenovo',
                'model' => 'Legion 5',
                'price' => 1199.99,
                'stock' => 9,
                'image' => '1773123725_Asus-Tuf.jpg',
                'description' => 'High performance gaming laptop.',
                'ram' => '16GB',
                'storage' => '1TB SSD',
                'processor' => 'AMD Ryzen 7',
                'screen_size' => '15.6 inch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}